cvat/apps/dashboard/urls.py
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: MIT

from django.urls import path
from . import views

urlpatterns = [
    path('get_share_nodes', views.JsTreeView),
    path('', views.DashboardView),
]

cvat/urls.py
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: MIT

"""CVAT URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.apps import apps
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cvat.apps.engine.urls')),
    path('dashboard/', include('cvat.apps.dashboard.urls')),
    path('django-rq/', include('django_rq.urls')),
    path('auth/', include('cvat.apps.authentication.urls')),
    path('documentation/', include('cvat.apps.documentation.urls')),
]

if apps.is_installed('cvat.apps.tf_annotation'):
    urlpatterns.append(path('tensorflow/annotation/', include('cvat.apps.tf_annotation.urls')))

if apps.is_installed('cvat.apps.git'):
    urlpatterns.append(path('git/repository/', include('cvat.apps.git.urls')))

if apps.is_installed('cvat.apps.auto_annotation'):
    urlpatterns.append(path('auto_annotation/', include('cvat.apps.auto_annotation.urls')))

if apps.is_installed('cvat.apps.log_viewer'):
    urlpatterns.append(path('analytics/', include('cvat.apps.log_viewer.urls')))

if apps.is_installed('silk'):
    urlpatterns.append(path('profiler/', include('silk.urls')))

cvat/apps/dashboard/models.py
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: MIT

from django.db import models

# Create your models here.

cvat/apps/engine/models.py
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: MIT

from django.db import models
from django.conf import settings

from django.contrib.auth.models import User

from io import StringIO
from enum import Enum

import shlex
import csv
import re
import os

class StatusChoice(Enum):
    ANNOTATION = 'annotation'
    VALIDATION = 'validation'
    COMPLETED = 'completed'

    @classmethod
    def choices(self):
        return tuple((x.name, x.value) for x in self)

    def __str__(self):
        return self.value

class SafeCharField(models.CharField):
    def get_prep_value(self, value):
        value = super().get_prep_value(value)
        if value:
            return value[:self.max_length]
        return value

class Task(models.Model):
    name = SafeCharField(max_length=256)
    size = models.PositiveIntegerField()
    path = models.CharField(max_length=256)
    mode = models.CharField(max_length=32)
    owner = models.ForeignKey(User, null=True, blank=True,
        on_delete=models.SET_NULL, related_name="owners")
    assignee = models.ForeignKey(User, null=True,  blank=True,
        on_delete=models.SET_NULL, related_name="assignees")
    bug_tracker = models.CharField(max_length=2000, blank=True, default="")
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now_add=True)
    overlap = models.PositiveIntegerField(default=0)
    z_order = models.BooleanField(default=False)
    flipped = models.BooleanField(default=False)
    source = SafeCharField(max_length=256, default="unknown")
    status = models.CharField(max_length=32, default=StatusChoice.ANNOTATION)

    # Extend default permission model
    class Meta:
        default_permissions = ()

    def get_upload_dirname(self):
        return os.path.join(self.path, ".upload")

    def get_data_dirname(self):
        return os.path.join(self.path, "data")

    def get_dump_path(self):
        name = re.sub(r'[\\/*?:"<>|]', '_', self.name)
        return os.path.join(self.path, "{}.xml".format(name))

    def get_log_path(self):
        return os.path.join(self.path, "task.log")

    def get_client_log_path(self):
        return os.path.join(self.path, "client.log")

    def get_image_meta_cache_path(self):
        return os.path.join(self.path, "image_meta.cache")

    def set_task_dirname(self, path):
        self.path = path
        self.save(update_fields=['path'])

    def get_task_dirname(self):
        return self.path

    def __str__(self):
        return self.name

class Segment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    start_frame = models.IntegerField()
    stop_frame = models.IntegerField()

    class Meta:
        default_permissions = ()

class Job(models.Model):
    segment = models.ForeignKey(Segment, on_delete=models.CASCADE)
    assignee = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    status = models.CharField(max_length=32, default=StatusChoice.ANNOTATION)
    max_shape_id = models.BigIntegerField(default=-1)

    class Meta:
        default_permissions = ()

class Label(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    name = SafeCharField(max_length=64)

    def __str__(self):
        return self.name

    class Meta:
        default_permissions = ()


def parse_attribute(text):
    match = re.match(r'^([~@])(\w+)=(\w+):(.+)?$', text)
    prefix = match.group(1)
    type = match.group(2)
    name = match.group(3)
    if match.group(4):
        values = list(csv.reader(StringIO(match.group(4)), quotechar="'"))[0]
    else:
        values = []

    return {'prefix':prefix, 'type':type, 'name':name, 'values':values}

class AttributeSpec(models.Model):
    label = models.ForeignKey(Label, on_delete=models.CASCADE)
    text  = models.CharField(max_length=1024)

    class Meta:
        default_permissions = ()

    def get_attribute(self):
        return parse_attribute(self.text)

    def is_mutable(self):
        attr = self.get_attribute()
        return attr['prefix'] == '~'

    def get_type(self):
        attr = self.get_attribute()
        return attr['type']

    def get_name(self):
        attr = self.get_attribute()
        return attr['name']

    def get_default_value(self):
        attr = self.get_attribute()
        return attr['values'][0]

    def get_values(self):
        attr = self.get_attribute()
        return attr['values']

    def __str__(self):
        return self.get_attribute()['name']


class AttributeVal(models.Model):
    # TODO: add a validator here to be sure that it corresponds to self.label
    id = models.BigAutoField(primary_key=True)
    spec = models.ForeignKey(AttributeSpec, on_delete=models.CASCADE)
    value = SafeCharField(max_length=64)

    class Meta:
        abstract = True
        default_permissions = ()


class Annotation(models.Model):
    job   = models.ForeignKey(Job, on_delete=models.CASCADE)
    label = models.ForeignKey(Label, on_delete=models.CASCADE)
    frame = models.PositiveIntegerField()
    group_id = models.PositiveIntegerField(default=0)
    client_id = models.BigIntegerField(default=-1)

    class Meta:
        abstract = True

class Shape(models.Model):
    occluded = models.BooleanField(default=False)
    z_order = models.IntegerField(default=0)

    class Meta:
        abstract = True
        default_permissions = ()

class BoundingBox(Shape):
    id = models.BigAutoField(primary_key=True)
    xtl = models.FloatField()
    ytl = models.FloatField()
    xbr = models.FloatField()
    ybr = models.FloatField()

    class Meta:
        abstract = True
        default_permissions = ()

class PolyShape(Shape):
    id = models.BigAutoField(primary_key=True)
    points = models.TextField()

    class Meta:
        abstract = True
        default_permissions = ()

class LabeledBox(Annotation, BoundingBox):
    pass

class LabeledBoxAttributeVal(AttributeVal):
    box = models.ForeignKey(LabeledBox, on_delete=models.CASCADE)

class LabeledPolygon(Annotation, PolyShape):
    pass

class LabeledPolygonAttributeVal(AttributeVal):
    polygon = models.ForeignKey(LabeledPolygon, on_delete=models.CASCADE)

class LabeledPolyline(Annotation, PolyShape):
    pass

class LabeledPolylineAttributeVal(AttributeVal):
    polyline = models.ForeignKey(LabeledPolyline, on_delete=models.CASCADE)

class LabeledPoints(Annotation, PolyShape):
    pass

class LabeledPointsAttributeVal(AttributeVal):
    points = models.ForeignKey(LabeledPoints, on_delete=models.CASCADE)

class ObjectPath(Annotation):
    id = models.BigAutoField(primary_key=True)
    shapes = models.CharField(max_length=10, default='boxes')

class ObjectPathAttributeVal(AttributeVal):
    track = models.ForeignKey(ObjectPath, on_delete=models.CASCADE)

class TrackedObject(models.Model):
    track = models.ForeignKey(ObjectPath, on_delete=models.CASCADE)
    frame = models.PositiveIntegerField()
    outside = models.BooleanField(default=False)
    class Meta:
        abstract = True
        default_permissions = ()

class TrackedBox(TrackedObject, BoundingBox):
    pass

class TrackedBoxAttributeVal(AttributeVal):
    box = models.ForeignKey(TrackedBox, on_delete=models.CASCADE)

class TrackedPolygon(TrackedObject, PolyShape):
    pass

class TrackedPolygonAttributeVal(AttributeVal):
    polygon = models.ForeignKey(TrackedPolygon, on_delete=models.CASCADE)

class TrackedPolyline(TrackedObject, PolyShape):
    pass

class TrackedPolylineAttributeVal(AttributeVal):
    polyline = models.ForeignKey(TrackedPolyline, on_delete=models.CASCADE)

class TrackedPoints(TrackedObject, PolyShape):
    pass

class TrackedPointsAttributeVal(AttributeVal):
    points = models.ForeignKey(TrackedPoints, on_delete=models.CASCADE)

cvat/apps/dashboard/views.py
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: MIT

from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest
from django.shortcuts import redirect
from django.shortcuts import render
from django.conf import settings
from cvat.apps.authentication.decorators import login_required

from cvat.apps.engine.models import Task as TaskModel, Job as JobModel
from cvat.settings.base import JS_3RDPARTY

import os

def ScanNode(directory):
    if '..' in directory.split(os.path.sep):
        return HttpResponseBadRequest('Permission Denied')

    act_dir = os.path.normpath(settings.SHARE_ROOT + directory)
    result = []

    nodes = os.listdir(act_dir)
    files = filter(os.path.isfile, map(lambda f: os.path.join(act_dir, f), nodes))
    dirs = filter(os.path.isdir, map(lambda d: os.path.join(act_dir, d), nodes))

    for d in dirs:
        name = os.path.basename(d)
        children = len(os.listdir(d)) > 0
        node = {'id': directory + name + '/', 'text': name, 'children': children}
        result.append(node)

    for f in files:
        name = os.path.basename(f)
        node = {'id': directory + name, 'text': name, "icon" : "jstree-file"}
        result.append(node)

    return result

@login_required
def JsTreeView(request):
    node_id = None
    if 'id' in request.GET:
        node_id = request.GET['id']

    if node_id is None or node_id == '#':
        node_id = '/'
        response = [{"id": node_id, "text": node_id, "children": ScanNode(node_id)}]
    else:
        response = ScanNode(node_id)

    return JsonResponse(response, safe=False,
        json_dumps_params=dict(ensure_ascii=False))


@login_required
def DashboardView(request):
    query_name = request.GET['search'] if 'search' in request.GET else None
    query_job = int(request.GET['jid']) if 'jid' in request.GET and request.GET['jid'].isdigit() else None
    task_list = None

    if query_job is not None and JobModel.objects.filter(pk = query_job).exists():
        task_list = [JobModel.objects.select_related('segment__task').get(pk = query_job).segment.task]
    else:
        task_list = list(TaskModel.objects.prefetch_related('segment_set__job_set').order_by('-created_date').all())
        if query_name is not None:
            task_list = list(filter(lambda x: query_name.lower() in x.name.lower(), task_list))

    task_list = list(filter(lambda task: request.user.has_perm(
        'engine.task.access', task), task_list))

    return render(request, 'dashboard/dashboard.html', {
        'data': task_list,
        'max_upload_size': settings.LOCAL_LOAD_MAX_FILES_SIZE,
        'max_upload_count': settings.LOCAL_LOAD_MAX_FILES_COUNT,
        'base_url': "{0}://{1}/".format(request.scheme, request.get_host()),
        'share_path': os.getenv('CVAT_SHARE_URL', default=r'${cvat_root}/share'),
        'js_3rdparty': JS_3RDPARTY.get('dashboard', []),
    })

cvat/apps/dashboard/templates/dashboard/dashboard.html
<!--
    Copyright (C) 2018 Intel Corporation

    SPDX-License-Identifier: MIT
-->
{% extends 'engine/base.html' %}
{% load static %}
{% load pagination_tags %}

{% block head_title %}
    CVAT Dashboard
{% endblock %}

{% block head_css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/stylesheet.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/js/3rdparty/jstree/themes/default/style.css' %}">
{% endblock %}

{% block head_js_3rdparty %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'dashboard/js/3rdparty/jstree/jstree.js' %}"></script>
    {% for js_file in js_3rdparty %}
        <script type="text/javascript" src="{% static js_file %}" defer></script>
    {% endfor %}
{% endblock %}

{% block head_js_cvat %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'dashboard/js/dashboard.js' %}"></script>
    <script type="text/javascript" src="{% static 'engine/js/listener.js' %}"></script>
    <script type="text/javascript" src="{% static 'engine/js/labelsInfo.js' %}"></script>
    <script type="text/javascript" src="{% static 'engine/js/shapes.js' %}"></script>
    <script type="text/javascript" src="{% static 'engine/js/annotationParser.js' %}"></script>
    <script type="text/javascript" src="{% static 'engine/js/server.js' %}"></script>
    <script>
        window.maxUploadSize = {{ max_upload_size }};
        window.maxUploadCount = {{ max_upload_count }};
    </script>
{% endblock %}

{% block content %}
    <div id="content">
        <center>
            <table style="width: 65%;">
                <tr>
                    <td><button id="dashboardCreateTaskButton" class="regular h1"> Create New Task </button></td>
                    <td>
                        <div style="width: 300px; float: right;">
                            <input type="text" id="dashboardSearchInput" class="regular h1" placeholder="Search.." name="search">
                            <button id="dashboardSearchSubmit" class="regular h1"> &#x1F50D; </button>
                        </div>
                    </td>
                </tr>
            </table>
        </center>

        {% autopaginate data %}
        <div style="float: left; width: 100%">
            {% for item in data %}
                {% include "dashboard/task.html" %}
            {% endfor %}
        </div>
        <center>{% paginate %}</center>
    </div>

    <div id="dashboardCreateModal" class="modal hidden">
        <form id="dashboardCreateContent" class="modal-content" autocomplete="on" onsubmit="return false">
            <center>
                <label class="semiBold h1"> Task Configuration </label>
            </center>

            <table style="width: 100%; text-align: left;">
                <tr>
                    <td style="width: 25%"> <label class="regular h2"> Name: </label> </td>
                    <td> <input type="text" id="dashboardNameInput" class="regular" style="width: 90%"/> </td>
                </tr>
                <tr>
                    <td> <label class="regular h2"> Labels: </label> </td>
                    <td> <input type="text" id="dashboardLabelsInput" class="regular" style="width: 90%" title='
Example:
car @select=color:blue,red,black ~checkbox=parked:true
@text=plate:"" @select=model:volvo,mazda,bmw
~radio=quality:good,bad

Specification:
<prefix>checkbox=id:true/false
<prefix>radio=id:name1,name2,...
<prefix>number=id:min,max,step
<prefix>text=id:"default value"
<prefix>select=id:value1,value2,...

<prefix> can be @ for unique properties and ~ for properties
which can change its value during lifetime of the object.
Default value for all elements is the first value after ":".

For "select" and "radio" types the special value is available: "__undefined__".
Specify the value FIRST if the attribute should be annotated explicitly.
Example: @select=race:__undefined__,skip,asian,black,caucasian,other'/>
                </td>
                </tr>
                <tr>
                    <td> <label class="regular h2"> Bug Tracker: </label> </td>
                    <td> <input type="text" id="dashboardBugTrackerInput" class="regular" style="width: 90%", placeholder="Please specify full URL"/> </td>
                </tr>
                <tr>
                    <td> <label class="regular h2"> Source: </label> </td>
                    <td>
                        <input id="dashboardLocalSource" type="radio" name="sourceType" value="local" checked=true/> <label for="dashboardLocalSource" class="regular h2" for="localSource"> Local </label>
                        <br> <input id="dashboardShareSource" type="radio" name="sourceType" value="share"/> <label for="dashboardShareSource" class="regular h2" for="shareSource"> Share </label>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label class="regular h2"> Flip images </label>
                    </td>
                    <td>
                        <input type="checkbox" id="dashboardFlipImages"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label class="regular h2"> Z-Order </label>
                    </td>
                    <td>
                        <input type="checkbox" id="dashboardZOrder"/>
                    </td>
                </tr>
                <tr>
                        <td>
                            <label class="regular h2"> Overlap Size </label>
                        </td>
                        <td>
                            <input type="number" id="dashboardOverlap" class="regular" max="50000" min="0" value="0" disabled=true/>
                            <input type="checkbox" id="dashboardCustomOverlap" title="Custom overlap size"/>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label class="regular h2"> Segment Size </label>
                        </td>
                        <td>
                            <input type="number" id="dashboardSegmentSize" class="regular" max="50000" min="100" value="5000" disabled=true/>
                            <input type="checkbox" id="dashboardCustomSegment" title="Custom segment size"/>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label class="regular h2"> Image Quality </label>
                        </td>
                        <td>
                            <input type="number" id="dashboardImageQuality" class="regular" style="width: 4.5em;" max="95" min="1" value="50" disabled=true/>
                            <input type="checkbox" id="dashboardCustomQuality" title="Custom image quality"/>
                        </td>
                    </tr>
            </table>


            <div style="text-align: left;">
                <div>
                    <button id="dashboardSelectFiles" class="regular h2"> Select Files </button>
                    <label id="dashboardFilesLabel" class="regular h2" style="margin-left: 10px"> No Files </label>
                    <input id="dashboardLocalFileSelector" type="file" style="display: none" multiple/>
                </div>
            </div>
            <div style="width: 100%; height: 14%; padding-top: 10px;">
                <div style="float: right; width: 35%; height: 50px;">
                    <button id="dashboardCancelTask" class="regular h2"> Cancel </button>
                    <button id="dashboardSubmitTask" class="regular h2"> Submit </button>
                </div>
                <div style="float: left; height: 50px;  overflow: auto; width: 100%; height: auto; word-break: break-word;">
                    <label id="dashboardCreateTaskMessage" class="regular h2 selectable" style="float:left;">  </label>
                </div>
            </div>
        </form>
    </div>

    <div id="dashboardShareBrowseModal" class="modal hidden">
        <div style="width: 600px; height: 400px;" class="modal-content noSelect">
            <center> <label class="regular h1"> {{ share_path }} </label> </center>
            <div id="dashboardShareBrowser"> </div>
            <center>
                <button id="dashboardCancelBrowseServer" class="regular h2" style="margin: 0px 10px"> Cancel </button>
                <button id="dashboardSubmitBrowseServer" class="regular h2" style="margin: 0px 10px"> Submit </button>
            </center>
        </div>
    </div>

    <div id="dashboardUpdateModal" class="modal hidden">
        <div id="dashboardUpdateContent" class="modal-content">
            <input id="dashboardOldLabels" type="text" readonly=true placeholder="Please Wait.." class="regular h2">
            <input id="dashboardNewLabels" type="text" placeholder="New Labels" class="regular h2">
            <center>
                <button id="dashboardCancelUpdate" class="regular h2"> Cancel </button>
                <button id="dashboardSubmitUpdate" class="regular h2"> Update </button>
            </center>
        </div>
    </div>
{% endblock %}

cvat/apps/dashboard/templates/dashboard/task.html
<!--
    Copyright (C) 2018 Intel Corporation

    SPDX-License-Identifier: MIT
-->
<div class="dashboardTaskUI" id="dashboardTask_{{item.id}}">
    <center class="dashboardTitleWrapper">
        <label class="semiBold h1 dashboardTaskNameLabel selectable"> {{ item.name }} </label>
    </center>
    <center class="dashboardTitleWrapper">
        <label class="regular dashboardStatusLabel"> {{ item.status }} </label>
    </center>
    <div class="dashboardTaskIntro" style='background-image: url("/get/task/{{item.id}}/frame/0")'>  </div>
    <div class="dashboardButtonsUI">
        <button class="dashboardDumpAnnotation regular dashboardButtonUI"> Dump Annotation </button>
        <button class="dashboardUploadAnnotation regular dashboardButtonUI"> Upload Annotation </button>
        <button class="dashboardUpdateTask regular dashboardButtonUI"> Update Task </button>
        <button class="dashboardDeleteTask regular dashboardButtonUI"> Delete Task </button>
         {%if item.bug_tracker %}
            <button class="dashboardOpenTrackerButton regular dashboardButtonUI"> Open Bug Tracker </button>
            <a class="dashboardBugTrackerLink" href='{{item.bug_tracker}}' style="display: none;"> </a>
        {% endif %}
    </div>
    <div class="dashboardJobsUI">
        <center class="dashboardTitleWrapper">
            <label class="regular h1"> Jobs </label>
        </center>
        <table class="dashboardJobList regular">
            {% for segm in item.segment_set.all %}
                {% for job in segm.job_set.all %}
                    <tr>
                        <td> <a href="{{base_url}}?id={{job.id}}"> {{base_url}}?id={{job.id}} </a> </td>
                    </tr>
                {% endfor %}
            {% endfor %}
        </table>
    </div>
</div>